from pathlib import Path


def test_settings_ui_exposes_archivist_web_clipper_and_translation_controls():
    html = (Path(__file__).resolve().parents[1] / "static" / "settings.html").read_text(
        encoding="utf-8"
    )

    expected_snippets = [
        'id="task-translation-enabled"',
        'id="task-translation-provider"',
        'id="task-translation-model"',
        'id="task-embedding-enabled"',
        'id="task-embedding-provider"',
        'id="task-embedding-model"',
        'id="task-archivist-enabled"',
        'id="task-archivist-provider"',
        'id="task-archivist-model"',
        'id="task-transcript-model"',
        'id="task-transcript-retry-hours"',
        'id="source-web-clipper-enabled"',
        'id="source-web-clipper-note-dirs"',
        'id="source-web-clipper-attachment-dirs"',
        'id="source-pi-skills-enabled"',
        'id="source-pi-skills-default-provider"',
        'id="source-pi-skills-default-model"',
        'id="source-pi-skills-output-dir"',
        'id="source-pi-skills-run-skill"',
        'id="source-pi-skills-prompt"',
        'id="source-pi-skills-input-paths"',
        'id="overview-providers"',
        'id="overview-connectors"',
        'id="overview-skills"',
        'id="overview-okf"',
        'id="overview-what-happened"',
        'id="overview-what-stuck"',
        'id="overview-run-next"',
        'id="health-sources"',
        'id="health-events"',
        'id="health-queues"',
        'id="health-stale-pages"',
        'id="health-compiler-runs"',
        'id="health-stuck"',
        'id="health-lineage-pages"',
        'id="health-lineage-files"',
        'id="health-llm-cost"',
        'id="health-llm-calls"',
        'id="health-source-table"',
        'id="health-sessions-table"',
        'id="health-compiler-list"',
        'id="health-stuck-list"',
        'id="health-lineage-list"',
        'id="health-llm-expensive-runs"',
        'id="health-llm-source-totals"',
        'id="health-llm-task-totals"',
        'id="health-errors"',
        'id="automation-archivist-enabled"',
        'id="automation-archivist-run-on-startup"',
        'id="automation-archivist-interval-hours"',
        'id="path-wiki"',
        'id="path-system"',
        'id="path-archivist-topics"',
        'id="runtime-archivist-registry"',
        'id="runtime-archivist-corpus"',
        'id="runtime-connectors-summary"',
        'id="runtime-config-groups"',
        'data-tab="archivist"',
        'id="archivist-route-summary"',
        'id="archivist-registry-path"',
        'id="archivist-registry-editor"',
        'id="archivist-topic-count"',
        'id="archivist-corpus-summary"',
        'id="archivist-topics-list"',
        'id="runtime-web-clipper-watch-dirs"',
        'data-tab="stats">Overview</button>',
        'data-tab="pipeline">Sources &amp; Skills</button>',
        'data-tab="archivist">Wiki &amp; Archivist</button>',
        'data-tab="security">Security</button>',
        'data-tab="paths">Advanced</button>',
        '<h2 class="card-title">Advanced: Model Providers</h2>',
        '<h2 class="card-title">Advanced: Task Routing</h2>',
        'id="security-auth-summary"',
        'id="security-prompt-summary"',
        'id="security-side-effects"',
        'id="security-dashboard-stats"',
        'id="security-artifacts-total"',
        'id="security-findings-by-source"',
        'id="security-quarantine-list"',
        'id="security-redactions"',
        'id="security-strict-failures"',
        'id="security-okf-lint-button"',
        'id="security-security-lint-button"',
        'id="security-okf-lint-download"',
        'id="security-security-lint-download"',
        'id="security-lint-result"',
        "const TASK_ROUTE_KEYS = ['tags', 'summary', 'alt_text', 'transcript', 'translation', 'embedding', 'archivist'];",
        "function showTab(tabName)",
        "function renderProviderModels(name, provider)",
        "function updateTaskModelDropdown(task)",
        "function formatConnectorRuntimeSummary(group)",
        "function formatConnectorBudgetSummary(budgets)",
        "function formatSecurityRuntimeSummary(security)",
        "function renderSecurityDashboard(security)",
        "function renderAdminStatusDashboard(status)",
        "function renderHealthStuck(rows)",
        "function renderLineagePages(lineage)",
        "function renderLLMExpensiveRuns(rows)",
        "function renderLLMTotals(rows, key, emptyText)",
        "async function runSettingsLint(kind)",
        "function formatGroupedRuntimeSummary(groups)",
        "function runPiSkill(options = {})",
        "function updateOverviewRuntime(groups)",
        "function renderPiSkillOptions(piSkills)",
        "async function loadArchivistRegistry()",
        "async function saveArchivistRegistry()",
        "async function runArchivistTopics(options = {})",
        "async function runArchivistTopic(topicId, options = {})",
        "async function queueArchivistForce(topicId)",
        "async function clearArchivistForce(topicId)",
        'href="/static/thoth.png"',
        'src="/static/thoth.png"',
        "'anthropic': 'ANTHROPIC_API'",
        "'openrouter': 'OPEN_ROUTER_API_KEY'",
    ]

    for snippet in expected_snippets:
        assert snippet in html
