"""Wiki pages/summaries -> projections, never source replacements (checklist 4, row 8).

Thoth wiki pages (``core/wiki_contract.WikiPageSpec``, compiled by
``core/wiki_updater.py`` / ``core/wiki_capture_compiler.py``) are *derived
projections*: every page records its exact inputs
(``source_paths``/``event_ids``/``semantic_candidate_ids``), an
``input_hash``, and ``change_provenance`` (``core/wiki_change_provenance``),
so any page can be rebuilt from canonical state by re-running the
compilers. They are therefore NOT canonical CCF Records and the mapping
layer does not emit them by default.

Rebuild path (projection, per checklist section 5): once capture events,
artifacts, utterances, entities, and assertions are canonical CCF state,
the wiki is regenerated by replaying the same compilers over that state —
``input_hash`` comparison detects drift, and a page whose inputs are
unchanged rebuilds byte-identical frontmatter provenance.

For operators who still want pages *visible* inside an archive, this module
can emit a page as a generated ``experience.artifact`` with
``artifact_role="wiki_projection"`` — but only with exact evidence: a
``ccf.derived_from`` Link to every mapped input object is mandatory, so a
projection can never masquerade as a source. The page markdown itself stays
in the vault; the artifact Record points at it by path and content hash.
"""

from __future__ import annotations

from ccf.ids import parse_id
from ccf.producer import Producer

from ccf.thothmap.context import (
    MapContext,
    MappedSubmissions,
    ThothMapError,
    claims,
    occurred_at,
    origin,
    require_str,
    require_urn,
)


def wiki_projection_submissions(
    producer: Producer,
    ctx: MapContext,
    snapshot: dict,
    *,
    source_ccf_id: str,
    evidence_ccf_ids: list[str],
    run_ccf_id: str | None = None,
    revision: str | int | None = "1",
) -> MappedSubmissions:
    """Emit a wiki page as a projection artifact with exact evidence Links.

    Snapshot keys (WikiPageSpec fields): ``slug``, ``title``, ``summary``,
    ``kind``, ``input_hash``, ``source_paths``, ``event_ids``,
    ``semantic_candidate_ids``, ``updated_at``/``created_at``.

    ``evidence_ccf_ids`` must reference the mapped CCF objects the page was
    compiled from and must be non-empty — a projection without resolvable
    inputs cannot be rebuilt and is refused. The artifact always names its
    rebuild inputs in extensions so ``input_hash`` drift is detectable from
    the canonical record alone.
    """
    require_urn(source_ccf_id, "record", field="source_ccf_id")
    if not evidence_ccf_ids:
        raise ThothMapError(
            "wiki projection requires evidence: derived_from links to its exact inputs"
        )
    for evidence_id in evidence_ccf_ids:
        try:
            parse_id(evidence_id)
        except Exception as exc:
            raise ThothMapError(f"invalid evidence URN: {evidence_id!r}") from exc
    if run_ccf_id is not None:
        require_urn(run_ccf_id, "record", field="run_ccf_id")

    slug = require_str(snapshot, "slug", what="wiki page")
    title = require_str(snapshot, "title", what="wiki page")
    input_hash = snapshot.get("input_hash")

    record = producer.new_record(
        type="experience.artifact",
        claims=claims(ctx, basis="deterministic_derivation", asserted_by=producer.producer_id),
        occurred_at=occurred_at(snapshot["updated_at"]) if snapshot.get("updated_at") else None,
        origin=origin(source_ccf_id, f"wiki:{slug}", revision),
        payload={
            "name": f"{slug}.md",
            "media_type": "text/markdown",
            "description": snapshot.get("summary") or title,
            "external_uri": None,
            "artifact_role": "wiki_projection",
            "extensions": {
                "thoth_wiki_slug": slug,
                "thoth_wiki_kind": snapshot.get("kind"),
                "thoth_input_hash": input_hash,
                "thoth_source_paths": list(snapshot.get("source_paths") or []),
                "thoth_event_ids": list(snapshot.get("event_ids") or []),
                "thoth_semantic_candidate_ids": list(
                    snapshot.get("semantic_candidate_ids") or []
                ),
            },
        },
    )
    result = MappedSubmissions(records=[record])
    for evidence_id in dict.fromkeys(evidence_ccf_ids):
        result.links.append(
            producer.new_link(
                type="ccf.derived_from",
                from_id=record["id"],
                to_id=evidence_id,
                claims=claims(ctx),
                selector={},
            )
        )
    if run_ccf_id is not None:
        result.links.append(
            producer.new_link(
                type="ccf.generated_by",
                from_id=record["id"],
                to_id=run_ccf_id,
                claims=claims(ctx),
                selector={},
            )
        )
    return result
